Idata =[
    {
        "name":"avinash",
        "followers":2134
    },
    {
        "name":"bapu",
        "followers":213
    },
    {
        "name":"salunke",
        "followers":21
    },
    {
        "name":"ram",
        "followers":2190
    },
    {
        "name":"kisan",
        "followers":321
    },
    {
        "name":"aniket",
        "followers":8765
    },
    {
        "name":"aba",
        "followers":3232
    },
    {
        "name":"om",
        "followers":908976
    },
    {
        "name":"pp",
        "followers":34567
    },
    {
        "name":"mahesh",
        "followers":234567
    },
    {
        "name":"jalindar",
        "followers":986764542
    },
    {
        "name":"bal",
        "followers":2345679875
    }
]